### ISSUE TITLE
Search with no results crashes

### ISSUE THREAD

**Issue by ggorlen** [kajchang/SFPL#10]
```py
for page in sfpl.Search('asdasfssfasfs search that has no results').getResults(pages=2):
    print(page)
```

gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\greg\Desktop\SFPL\sfpl\sfpl.py", line 543, in getResults
    if math.ceil(int(re.match(book_page_regex, soup.find(string=re.compile(book_page_regex))).group(1).replace(',', '')) / 10) < x:
  File "C:\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**Comment by ggorlen** [comment]
This also appears to fail on pages with 1 result. The regex could use `?` to make the plural `s` optional:

```py
book_page_regex = '[\d,]+ to [\d,]+ of ([\d,]+) results?'
list_page_regex = '[\d,]+ - [\d,]+ of ([\d,]+) items?'
```

Sample input that has 1 result at the moment:

```py
for page in sfpl.Search('Everything Keeps Dissolving').getResults(pages=2):
    print(page)
```

(this search also fails for another reason, https://github.com/kajchang/SFPL/issues/11)
